### ISSUE TITLE
[FEAT] Upload the chrome addons to microsoft edge extensions store

### ISSUE THREAD

**Issue by yoke88** [cars10/elasticvue#15]
**Description**
Upload the chrome addons to microsoft edge extensions store

**Additional context**
we can not access chrome store in china ,but we can access microsoft store to download edge extension, so please upload this chrome extension to microsoft store or provide the crx file

**Comment by cars10** [comment]
Thank you for the suggestion. I just submitted the extension to the store, i will update this post with a link once it is approved.

**Comment by yoke88** [comment]
another question,

how can i config multiple cors allowed origin, the config below does not work:
``` yaml
http.cors.enabled: true
      http.cors.allow-origin: 
        - "https://app.elasticvue.com"
        - "chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa"
      http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization,X-Auth-Token
      http.cors.allow-credentials: true
```

it can only works like below:
``` yaml
      http.cors.enabled: true
      http.cors.allow-origin: "https://app.elasticvue.com"
      http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization,X-Auth-Token
      http.cors.allow-credentials: true
```
