### ISSUE TITLE
[BUG] - Cannot connect to localhost opensearch no auth

### ISSUE THREAD

**Issue by Danipulok** [cars10/elasticvue#222]
**Description**
Cannot connect to localhost docker-running opensearch (is it a problem it's opensearch and not elasticsearch?). With chrome and postman everything works with GET and POST requests though.

**Steps To Reproduce**
List the steps to reproduce your problem:
0. Run opensearch via docker-compose.
1. Open elasticvue
2. Click on `Add elasticsearch cluster`, enter: `default cluster`, `http://localhost:9200`
3. Get following:
`403 Forbidden
Can't connect to your cluster. Please make sure that
Your cluster is reachable via http://localhost:9200/`

**Screenshots**
![image](https://github.com/cars10/elasticvue/assets/45077699/605ea860-e2a1-4185-92c3-fd43491d44a2)
![image](https://github.com/cars10/elasticvue/assets/45077699/d5c990ee-77d2-4e8b-a198-dff00dc871b5)
![image](https://github.com/cars10/elasticvue/assets/45077699/46911cc4-76dc-4761-aa92-496d7e2bf603)
![image](https://github.com/cars10/elasticvue/assets/45077699/33cc31ec-9ae6-4de5-b40c-6e25922e422d)

**Environment (please include the following information):**
* Elasticsearch version:
* Operating system: Windows
* Browser + version: Chrome 122.0.6261.131 (Official Build) (64-bit)
* Elasticvue version: Elasticvue 1.0.4-stable
* How are you running elasticvue?: browser extension

**Additional context**
Docker-compose file:
```yaml
  elasticsearch:
      image: opensearchproject/opensearch:1.3.10
      ports:
        - "127.0.0.1:9200:9200"
        - "127.0.0.1:9300:9300"
      environment:
        network.host: 0.0.0.0
        discovery.type: single-node
        bootstrap.memory_lock: 'true'
        http.cors.enabled: 'true'
        http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358  # to be able to use dejavu web browser
        http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        http.cors.allow-credentials: 'true'
        plugins.security.disabled: 'true'  # required for opensearch to turn off https
        ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      ulimits:
        memlock:
          soft: -1
          hard: -1
```

Postman has `no auth`.

If there is some stupid mistake on my side, sorry in advance.

**Comment by cars10** [comment]
Try adding the extension url to the `http.cors.allow-origin` setting. You don't normally have to configure CORS when using the browser extensions, but whant you DO set it anyway, you have to set it correctly. Elasticvue tells you exactly what you need to do while you try to connect, but basically just add the extension url (yes, the `chrome-extension//werid-string`) to your allow-origin, then it should work.

**Comment by Danipulok** [comment]
@cars10 thank you so much for helping even though it wasn't your problem!
Appreciate a lot. Removing cors for local testing helped!

**Comment by cars10** [comment]
Alright, glad that you could solve the problem :) You can also use elasticvue desktop to completely ignore CORS & SSL related issues.

**Comment by Danipulok** [comment]
Thanks so much again :3
Downloaded the desktop version too, seems really nice!

**Comment by wideweide** [comment]
> @cars10 thank you so much for helping even though it wasn't your problem! Appreciate a lot. Removing cors for local testing helped!

may you paste your config for a example?
I try the code ,but not work

```
version: "3.8"

services:
  service-es1:
    image: 127.0.0.1:5000/elasticsearch:6.5.4
    hostname: service-es1


    environment:
      - node.name=node-v1
      - cluster.name=docker-cluster
      - path.repo=my_backup_location
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin="http://192.168.1.250:8214, moz-extension://.*, chrome-extension://cpmmilfkofbeimbmgiclohpodggeheim"
      - http.cors.allow-credentials=true
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=Authorization,X-Requested-With,Content-Type,Content-Length,kbn-version,X-Security-Version
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.fd.ping_timeout=1000s
      - discovery.zen.fd.ping_retries=10
      - node.master=true
      - node.data=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
      - ES_JAVA_OPTS=-Xms1G -Xmx1G

```
