### ISSUE TITLE
[FEAT] Would it be possible to automatically import the “Predefined clusters” when opening Elasticvue?

### ISSUE THREAD

**Issue by stephane-klein** [cars10/elasticvue#254]
The `ELASTICVUE_CLUSTERS` parameter works correctly:

```
  elasticvue:
    image: cars10/elasticvue:1.0.10
    ports:
      - 8080:8080
    environment:
      - ELASTICVUE_CLUSTERS=[{"name":"docker-cluster","uri":"http://localhost:9200"}]
```

Feature request: Would it be possible to automatically import the “Predefined clusters” when opening Elasticvue?

![image](https://github.com/user-attachments/assets/b182d1e5-ff98-4051-a0ad-4b66f5b4f567)

Best regards,
Stéphane
